enable chef vault to encrypt workflow passwords

diff --git a/libs/dynamic_roles_script b/libs/dynamic_roles_script
--- a/libs/dynamic_roles_script
+++ b/libs/dynamic_roles_script
@@ -19,6 +19,18 @@ getValueFromPropFile () {
   echo $value
 }
 
+Decode_base64 () {
+  # $1 first input is an encrypted base64 string
+  echo "$1" | base64 -d &> /dev/null
+
+  if (($? != 0)); then
+    printf "Could not decode base64 string, $1, please check your encryption\n" >&2
+  return $?
+  fi
+
+  local decrypted_pass=$(echo "$1" | base64 -d)
+  echo $decrypted_pass
+}
 
 getFormatedStringListForiFixpack () {
 
@@ -26,7 +38,6 @@ getFormatedStringListForiFixpack () {
   
   # For example
   # INPUT workflow.18002.delta.repository.zip 8.5.5-WS-WAS-FP014-part1.zip; 8.5.5-WS-WAS-FP014-part2.zip; 8.5.5-WS-WAS-FP014-part3.zip test1.zip; test2; test3 test1.zip
-  
   # OUTPUT "workflow.18002.delta.repository.zip, 8.5.5-WS-WAS-FP014-part1.zip;8.5.5-WS-WAS-FP014-part2.zip;8.5.5-WS-WAS-FP014-part3.zip, test1.zip;test2;test3, test1.zip"
   local input_unformated_fixpack_names_arrary=( $1 )
   local input_unformated_fixpack_names_arrary_length=${#input_unformated_fixpack_names_arrary[*]}
@@ -89,7 +100,6 @@ Auto_Create_WORKFLOW_INSTALL_ROLE () {
   # Workflow02_node_os_admin_user=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE Workflow02_node_os_admin_user)
   Workflow01_node_os_admin_user=${Workflow01_node_os_admin_user:-"root"} 
   # Workflow02_node_os_admin_user=${Workflow02_node_os_admin_user:-"root"} 
-  # Common para
   var_Workflow_os_admin_user=${var_Workflow_os_admin_user:-"$Workflow01_node_os_admin_user"} 
 
   # "install_mode": "nonAdmin",
@@ -100,23 +110,21 @@ Auto_Create_WORKFLOW_INSTALL_ROLE () {
   #         "name": "$var_Workflow_baw_os_user_name",
   # Use "Workflow01_baw_os_user_name" as default input
   var_Workflow01_baw_os_user_name=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE Workflow01_baw_os_user_name)
-  # Common para
+ 
   var_Workflow_baw_os_user_name=${var_Workflow_baw_os_user_name:-"$var_Workflow01_baw_os_user_name"}
   local_Workflow_baw_os_user_home="/home/$var_Workflow_baw_os_user_name"
 
-  # Common para "gid": "$var_Workflow01_baw_os_user_gid",
+  # "gid": "$var_Workflow01_baw_os_user_gid",
   Workflow01_baw_os_user_gid=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE Workflow01_baw_os_user_gid)
   Workflow01_baw_os_user_gid=${Workflow01_baw_os_user_gid:-"workflowgroup"}
   var_Workflow_baw_os_user_gid=${var_Workflow_baw_os_user_gid:-"$Workflow01_baw_os_user_gid"}
 
-  # Common para
   var_Workflow_baw_os_user_shell=${var_Workflow_baw_os_user_shell:-"/bin/bash"}
 
   var_Workflow_product_version=${var_Workflow_product_version:-"18.0.0.1"}
   var_Workflow_im_version=${var_Workflow_im_version:-"1.8.9"}
   var_Workflow_features=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE Workflow_features)
 
-  # Comman para
   local_Workflow_install_dir="/home/${var_Workflow_baw_os_user_name}/IBM/Workflow"
   var_Workflow_baw_offering_id=${var_Workflow_baw_offering_id:-"com.ibm.bpm.ADV.v85"}
   var_Workflow_baw_offering_version=${var_Workflow_baw_offering_version:-"8.6.10018001"}
@@ -144,7 +152,6 @@ echo "ROLE: $BAW_CHEF_TEMP_DIR/$WORKFLOW_INSTALL_ROLE_FILE created"
 }
 
 
-# function Auto_Create_WORKFLOW_UPGRADE_ROLE
 Auto_Create_WORKFLOW_UPGRADE_ROLE () {
 
   
@@ -165,7 +172,6 @@ Auto_Create_WORKFLOW_UPGRADE_ROLE () {
   then
     local_node_hostnames=${local_node_hostnames:-"$var_Workflow01_name.$var_Workflow01_domain"}
   fi
-
 
   var_Workflow_cell_admin_username=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE Workflow_cell_admin_username)
   # var_Workflow_cell_admin_userpassword=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE Workflow_cell_admin_userpassword)
@@ -189,7 +195,6 @@ Auto_Create_WORKFLOW_UPGRADE_ROLE () {
   # Workflow01_fixpack_names=workflow.18002.delta.repository.zip
   # WAS_fixpack_names=8.5.5-WS-WAS-FP014-part1.zip; 8.5.5-WS-WAS-FP014-part2.zip; 8.5.5-WS-WAS-FP014-part3.zip
 
-
   var_Workflow_fixpack_names_tmp=( $(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE Workflow_fixpack_names) )
   var_WAS_fixpack_names_tmp=( $(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE WAS_fixpack_names) )
 
@@ -206,7 +211,6 @@ echo "ROLE: $BAW_CHEF_TEMP_DIR/$WORKFLOW_UPGRADE_ROLE_FILE created"
 }
 
 
-# function Auto_Create_WORKFLOW_APPLYIFIX_ROLE
 Auto_Create_WORKFLOW_APPLYIFIX_ROLE () {
 
 
@@ -264,7 +268,6 @@ echo "ROLE: $BAW_CHEF_TEMP_DIR/$WORKFLOW_APPLYIFIX_ROLE_FILE created"
 }
 
 
-# function Auto_Create_WORKFLOW_CREATE_SINGLECLUSTER_ROLE
 Auto_Create_WORKFLOW_CREATE_SINGLECLUSTER_ROLE () {
 
   #Role name is needed to be defined ahead of time
@@ -284,18 +287,15 @@ Auto_Create_WORKFLOW_CREATE_SINGLECLUSTER_ROLE () {
   Workflow01_baw_os_user_gid=${Workflow01_baw_os_user_gid:-"workflowgroup"}
   var_Workflow_baw_os_user_gid=${var_Workflow_baw_os_user_gid:-"$Workflow01_baw_os_user_gid"}
 
-
   # "node_hostname": "kvm-018074.test.local",
   var_Workflow01_name=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE Workflow01_node_name)
   var_Workflow01_domain=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE Workflow01_node_domain)
-  # "node_hostname": "kvm-018074.test.local",
+  # "node_hostname": "kvm-018075.test.local",
   var_Workflow02_name=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE Workflow02_node_name)
   var_Workflow02_domain=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE Workflow02_node_domain)
 
   # "ip_hostname_pairs": {}, key value pair
   # local_ip_hostname_pairs="$IHS_IP_ADDR"': '"$var_IHS01_name.$var_IHS01_domain","$WF01_IP_ADDR":"$var_Workflow01_name.$var_Workflow01_domain","$WF02_IP_ADDR":"$var_Workflow02_name.$var_Workflow02_domain" 
-  # unset var_Workflow02_name
-  # unset var_Workflow01_name
   if [ ! -z "$WF01_IP_ADDR" -a ! -z "$var_Workflow01_name" -a ! -z "$var_Workflow01_domain" ]
   then
     if [ ! -z "$WF02_IP_ADDR" -a ! -z "$var_Workflow02_name" -a ! -z "$var_Workflow02_domain" ] 
@@ -471,7 +471,7 @@ Auto_Create_WORKFLOW_CREATE_SINGLECLUSTER_ROLE () {
   #   "url": "",
   var_metering_url=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE metering_url)
   #   "apikey": ""
-  var_metering_apikey=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE metering_apikey)
+  # var_metering_apikey=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE metering_apikey)
 
 # be careful, donot indent these codes below, _EOF_
 eval "cat << _EOF_
@@ -482,7 +482,6 @@ echo "ROLE: $BAW_CHEF_TEMP_DIR/$WORKFLOW_v18_0_201806_CREATE_SINGLECLUSTER_ROLE_
 }
 
 
-# function Auto_Create_WORKFLOW_POST_DEPLOYMENT_ROLE
 Auto_Create_WORKFLOW_POST_DEPLOYMENT_ROLE () {
 
   #Role name is needed to be defined ahead of time
@@ -523,4 +522,66 @@ eval "cat << _EOF_
 _EOF_" > $BAW_CHEF_TEMP_DIR/$WORKFLOW_POST_DEPLOYMENT_ROLE_FILE
 
 echo "ROLE: $BAW_CHEF_TEMP_DIR/$WORKFLOW_POST_DEPLOYMENT_ROLE_FILE created"
+}
+
+
+# Return $RUNTIME_WORKFLOW_SECRETS_JSON
+Auto_Create_WORKFLOW_SECRETS () {
+
+  # The encrypted password
+  local var_ibm_im_repo_password_tmp=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE ibm_im_repo_password)
+  local var_ibm_sw_repo_password_tmp=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE ibm_sw_repo_password)
+
+  local var_Workflow_db2_instance_userpassword_tmp=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE Workflow_db2_instance_userpassword)
+  local var_Workflow_db2_fenced_userpassword_tmp=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE Workflow01_db2_fenced_userpassword)
+  local var_Workflow_db2_das_userpassword_tmp=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE Workflow01_db2_das_userpassword)
+
+  local var_Workflow_de_admin_userpassword_tmp=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE Workflow_de_admin_userpassword)
+  local var_Workflow_cell_admin_userpassword_tmp=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE Workflow_cell_admin_userpassword)
+
+  local var_Workflow_db2_instance_userpassword_config_tmp=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE Workflow_db2_instance_userpassword_config)
+
+  local var_Database_oracle_shareddb_userpassword_tmp=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE Database_oracle_shareddb_userpassword)
+  local var_Database_oracle_cellonlydb_userpassword_tmp=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE Database_oracle_cellonlydb_userpassword)
+  local var_Database_oracle_psdb_userpassword_tmp=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE Database_oracle_psdb_userpassword)
+  local var_Database_oracle_icndb_userpassword_tmp=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE Database_oracle_icndb_userpassword)
+  local var_Database_oracle_dosdb_userpassword_tmp=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE Database_oracle_dosdb_userpassword)
+  local var_Database_oracle_tosdb_userpassword_tmp=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE Database_oracle_tosdb_userpassword)
+  local var_Database_oracle_pdwdb_userpassword_tmp=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE Database_oracle_pdwdb_userpassword)
+  local var_Workflow_ps_pc_alias_password_tmp=${var_Workflow_ps_pc_alias_password:-""}
+
+  local var_metering_apikey_tmp=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE metering_apikey)
+
+  # Try to decrypt the encrypted password listed above
+  local var_ibm_im_repo_password=$(Decode_base64 $var_ibm_im_repo_password_tmp)
+  local var_ibm_sw_repo_password=$(Decode_base64 $var_ibm_sw_repo_password_tmp)
+
+  local var_Workflow_db2_instance_userpassword=$(Decode_base64 $var_Workflow_db2_instance_userpassword_tmp)
+  local var_Workflow_db2_fenced_userpassword=$(Decode_base64 $var_Workflow_db2_fenced_userpassword_tmp) 
+  local var_Workflow_db2_das_userpassword=$(Decode_base64 $var_Workflow_db2_das_userpassword_tmp) 
+
+  local var_Workflow_de_admin_userpassword=$(Decode_base64 $var_Workflow_de_admin_userpassword_tmp) 
+  local var_Workflow_cell_admin_userpassword=$(Decode_base64 $var_Workflow_cell_admin_userpassword_tmp) 
+
+  local var_Workflow_db2_instance_userpassword_config=$(Decode_base64 $var_Workflow_db2_instance_userpassword_config_tmp) 
+
+  local var_Database_oracle_shareddb_userpassword=$(Decode_base64 $var_Database_oracle_shareddb_userpassword_tmp)
+  local var_Database_oracle_cellonlydb_userpassword=$(Decode_base64 $var_Database_oracle_cellonlydb_userpassword_tmp) 
+  local var_Database_oracle_psdb_userpassword=$(Decode_base64 $var_Database_oracle_psdb_userpassword_tmp) 
+  local var_Database_oracle_icndb_userpassword=$(Decode_base64 $var_Database_oracle_icndb_userpassword_tmp)
+  local var_Database_oracle_dosdb_userpassword=$(Decode_base64 $var_Database_oracle_dosdb_userpassword_tmp) 
+  local var_Database_oracle_tosdb_userpassword=$(Decode_base64 $var_Database_oracle_tosdb_userpassword_tmp) 
+  local var_Database_oracle_pdwdb_userpassword=$(Decode_base64 $var_Database_oracle_pdwdb_userpassword_tmp)
+  local var_Workflow_ps_pc_alias_password=$(Decode_base64 $var_Workflow_ps_pc_alias_password_tmp) 
+
+  local var_metering_apikey=$(Decode_base64 $var_metering_apikey_tmp) 
+
+# be careful, donot indent these codes below, _EOF_
+readonly RUNTIME_WORKFLOW_SECRETS_JSON=$( eval "cat << _EOF_
+  $(< $WORKFLOW_SECRETS_TMPL_FILE)
+_EOF_" )
+
+echo "Workflow Secrets Generated"
+# TODO: For debug only, delete it before release
+echo "Workflow Secrets: $RUNTIME_WORKFLOW_SECRETS_JSON"
 }
