Add Upgrade and Applyifix for Single node

diff --git a/libs/utilities_script b/libs/utilities_script
--- a/libs/utilities_script
+++ b/libs/utilities_script
@@ -36,6 +36,21 @@ Decode_base64 () {
   echo $decrypted_pass
 }
 
+
+Create_Chef_Vaults () {
+
+  # Generate_CHEFVAULT 
+  WORKFLOW_SECRETS_TMPL_FILE=$workflow_secrets_TMPL_FILE
+  Auto_Create_WORKFLOW_SECRETS || return 1
+  # RUNTIME_WORKFLOW_SECRETS_JSON
+
+  if [ $( eval "knife vault list -M client | grep ^$BAW_CHEF_VAULT_NAME$" ) ]; then
+    knife vault delete $BAW_CHEF_VAULT_NAME $BAW_CHEF_VAULT_ITEM -M client -y 
+  fi
+  knife vault create $BAW_CHEF_VAULT_NAME $BAW_CHEF_VAULT_ITEM "$RUNTIME_WORKFLOW_SECRETS_JSON" -C "$SNODE_ON_CHEF_SERVER" -M client || { echo "Error when creating chef vault"; return 1; } 
+}
+
+
 ######## Monitor ########
 Monitor () {
 
