detect invalid utf-8 encode password

diff --git a/libs/utilities_script b/libs/utilities_script
--- a/libs/utilities_script
+++ b/libs/utilities_script
@@ -44,9 +44,15 @@ Decode_base64 () {
 
   local decrypted_pass=$(echo "$value" | base64 -d)
 
-  if [[ $decrypted_pass = *[![:ascii:]]* ]]; then
-    printf "\nWARNING, the value we decoded contains non-ASCII characters, the encrypted base64 string is $value and its key is $key\n\n" >&2
+  echo $decrypted_pass | iconv --from-code=UTF-8 &> /dev/null
+
+  if (($? != 0)); then
+    printf "\nError, invalid byte sequence in UTF-8 (ArgumentError), the encrypted base64 string is $value and its key is $key , please check your encryption\n\n" >&2
+    return 1
   fi
+  # if [[ $decrypted_pass = *[![:ascii:]]* ]]; then
+  #   printf "\nWARNING, the value we decoded contains non-ASCII characters, the encrypted base64 string is $value and its key is $key\n\n" >&2
+  # fi
 
   echo $decrypted_pass
 }
