Add validation and refactor codes before run

diff --git a/libs/utilities_script b/libs/utilities_script
--- a/libs/utilities_script
+++ b/libs/utilities_script
@@ -19,6 +19,16 @@ getValueFromPropFile () {
   echo $value
 }
 
+Validation_Prop() {
+
+  if (($# != 2)); then
+    echo "Usage: the first parameter is vaule, the second parameter is key in properties file"
+    return 1
+  fi
+
+  if [ -z "$1" ]; then echo "Validation Failed: $2 can not be empty in properties file"; return 1; fi
+}
+
 Decode_base64 () {
   # $1 key, description
   # $2 value, is an encrypted base64 string 
@@ -34,6 +44,52 @@ Decode_base64 () {
 
   local decrypted_pass=$(echo "$value" | base64 -d)
   echo $decrypted_pass
+}
+
+
+Load_Host_Name_Singlenode () {
+
+  # Get basic info
+  var_Workflow01_FQDN=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE workflow_host01_fqdn_name)
+
+  Validation_Prop "$var_Workflow01_FQDN"  "workflow_host01_fqdn_name" || return 1 
+
+  var_Workflow01_name=$(echo $var_Workflow01_FQDN | cut -d '.' -f1)
+}
+
+
+Load_Host_Name_Multinodes () {
+
+  # Get basic info
+  Load_Host_Name_Singlenode || return 1 
+
+  # "node_hostname": "kvm-018075.test.local",
+  var_Workflow02_FQDN=$(getValueFromPropFile $BAW_CHEF_PROPERTIES_FILE workflow_host02_fqdn_name)
+
+  Validation_Prop "$var_Workflow02_FQDN"  "workflow_host02_fqdn_name" || return 1 
+
+  if [ ! -z $(echo $var_Workflow01_FQDN | grep '\.' ) ]
+  then
+    var_Workflow01_domain=$(echo $var_Workflow01_FQDN | cut -d '.' -f2-)
+  fi
+
+  var_Workflow02_name=$(echo $var_Workflow02_FQDN | cut -d '.' -f1)
+  if [ ! -z $(echo $var_Workflow02_FQDN | grep '\.' ) ]
+  then
+    var_Workflow02_domain=$(echo $var_Workflow02_FQDN | cut -d '.' -f2-)
+  fi
+
+  if [ ! -z "$var_Workflow01_name" -a ! -z "$var_Workflow01_domain" ]
+  then
+    if [ ! -z "$var_Workflow02_name" -a ! -z "$var_Workflow02_domain" ]
+    then
+      local_node_hostnames="$var_Workflow01_name.$var_Workflow01_domain,$var_Workflow02_name.$var_Workflow02_domain"
+    else
+      local_node_hostnames="$var_Workflow01_name.$var_Workflow01_domain"
+    fi
+  else
+    local_node_hostnames="$var_Workflow02_name.$var_Workflow02_domain"
+  fi 
 }
 
 
